{
    'name':'Colab Consultancy Service',
    'category':'Job Portal',
    'summary':'Job Application Portal',
    'company':'Colab Consultancy Service',
    'description':'This is the job application portal applied in the webiste',
    'depends':['base','project','hr','mail','board','portal','docusign'],
    'data':[
        'report/candidate_summary.xml',
        'report/report_summary.xml',
        'report/header.xml',
        'views/inherit.xml',
        'data/sequence.xml',
        # 'views/website_template.xml',
        'views/job_template.xml',
        'views/inherit_website.xml',
        'security/security.xml',
        'security/job_desc.xml',
        "views/projectmaster.xml",
        'security/job_description.xml',
        "views/inherit_page_hr_job.xml",
        'views/language.xml',
        'views/menu.xml',
        'views/portal_changes.xml',
        "security/company_access.xml",
        'security/jd.xml',
        'security/new_access.xml',
        'security/ir.model.access.csv',
    ],
    'qweb': [],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
}
